Versions
qibogang/qibo pull request #7
Opened 2022-12-09 12:09 UTC by Edoardo-Pedicillo

We deploy the `latest` and `stable` documentation in this PR.
Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

2022-12-09 13:42 UTC, AleCandido commented on .github/workflows/deploy_doc.yml
> +          if [[ "${{ github.event_name }}" == "tag" ]]; then
Tag is scoped under `push` in the workflow file, are you sure the `github.event_name` would be `tag`?

2022-12-09 13:43 UTC, AleCandido commented on .github/workflows/deploy_doc.yml
> +    uses: qibogang/workflows/.github/workflows/deploy-sphinx-docs-to-ghpages.yml@versions
You can't use this action here, unfortunately for the time being you have to copy-paste the content above.

2022-12-13 11:25 UTC, AleCandido requested changes

2022-12-13 12:03 UTC, AleCandido approved these changes

2022-12-14 15:12 UTC, Edoardo-Pedicillo commented
@AleCandido, I agree. We can merge it.

2022-12-14 15:12 UTC, merged